language: swift 
osx_image: xcode8.2
script:
        - xcodebuild -version
        - xcodebuild -workspace HKProgressHUD.xcworkspace -list
        - xcodebuild clean build -sdk iphonesimulator -workspace HKProgressHUD.xcworkspace -scheme HKProgressHUD CODE_SIGNING_REQUIRED=NO
        - xcodebuild -scheme HudDemoTests -workspace HKProgressHUD.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPad Air 2,OS=10.2' clean build test
after_success:
        - bash <(curl -s https://codecov.io/bash)
